services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - "./frontend:/usr/share/nginx/html"
    # todo migrate to a dedicated build step with COPY
    # volumes are good for local development since they're live

  backend:
    image: backend
    build: ./backend
    ports:
      - "8081:8081"
    entrypoint: ["python3", "./server.py"]
    # todo migrate to a dedicated build step with COPY
    # volumes are good for local development since they're live